# Configuration for lintrunner https://github.com/suo/lintrunner

[[linter]]
code = 'FLAKE8'
include_patterns = [
    '**/*.py',
    '**/*.pyi',
]
exclude_patterns = [
    '.git/**',
    '.lintrunner/**',
    'docs/**',
]
command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'flake8_linter',
    '--docstring-convention=google',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    'flake8==5.0.4',
    'flake8-bugbear==22.10.27',
    'flake8-pyi==22.10.0',
    'dlint==0.13.0',
    'flake8-docstrings==1.6.0',
    'flake8-future-annotations==1.0.0',
]

[[linter]]
code = 'MYPY'
include_patterns = [
    'onnxscript/**/*.py',
    'onnxscript/**/*.pyi',
]
exclude_patterns = [
    # FIXME: Fix typing annotations in these files
    'onnxscript/converter_test.py',
    'onnxscript/converter.py',
    'onnxscript/evaluator_test.py',
    'onnxscript/evaluator.py',
    'onnxscript/onnx_types.py',
    'onnxscript/tests/eager_test.py',
    'onnxscript/tests/external_tensor_test.py',
    'onnxscript/tests/functions/**',
    'onnxscript/tests/loop_test.py',
    'onnxscript/tests/operator_test.py',
    'onnxscript/type_annotation_test.py',
]
command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'mypy_linter',
    '--config=pyproject.toml',
    '--show-disable',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    'mypy==0.991',
]

[[linter]]
code = 'BLACK-ISORT'
include_patterns = [
    '**/*.py',
]
exclude_patterns = [
    'onnxscript/tests/onnx_backend_test_code/**',
]
command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'black_isort_linter',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    'black==22.10.0',
    'isort==5.10.1',
]
is_formatter = true

[[linter]]
code = 'PYLINT'
include_patterns = [
    '**/*.py',
]
exclude_patterns = [
    'docs/examples/**',
    'docs/tutorial/examples/**',
    'onnxscript/converter_test.py',
    'onnxscript/tests/functions/**',
    'onnxscript/tests/models/**',
    'onnxscript/tests/onnx_backend_test_code/**',
]
command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'pylint_linter',
    '--rcfile=pyproject_pylint.toml',
    '--show-disable',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    'pylint==2.15.5',
]

[[linter]]
code = 'EDITORCONFIG-CHECKER'
include_patterns = ['**']
exclude_patterns = [
    '**/*.ipynb',
]
command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'editorconfig_checker_linter',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python',
    '-m',
    'lintrunner_adapters',
    'run',
    'pip_init',
    '--dry-run={{DRYRUN}}',
    'editorconfig-checker==2.6.2',
]
