# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python39:
      python.version: '3.9'
    Python38:
      python.version: '3.8'
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements-dev.txt
  displayName: 'Install dependencies'

- script: |
    python setup.py sdist
  displayName: 'package'

- script: |
    pytest -v onnxscript
  displayName: 'pytest'

- script: |
    python -m flake8 onnxscript --max-line-length 95 --exclude "**test/models/*.py"
  displayName: 'flake8'

- script: |
    python -m sphinx docs dist/html
  displayName: 'documentation'
