# Template steps for the release pipeline
parameters:
- name: is1ES
  displayName: 'Is 1ES pipeline'
  type: boolean
  default: false
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'
  displayName: 'Set Up Python'
- script: python -m pip install --upgrade pip build wheel
  displayName: 'Install Python build dependencies'
- script: python -m build
  displayName: 'Build ONNX Script wheel'
- task: CopyFiles@2
  displayName: 'Copy Python Wheel to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: 'dist'
    Contents: '*.*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- ${{ if eq(parameters.is1ES, false) }}:
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Python Wheel'
    inputs:
      ArtifactName: 'onnxscript'
- ${{ if eq(parameters.is1ES, true) }}:
  - task: 1ES.PublishPipelineArtifact@1
    displayName: 'Publish Python Wheel'
    inputs:
      ArtifactName: 'onnxscript'
      PathToPublish: '$(Build.ArtifactStagingDirectory)'