# Build the release version of the package and publish to artifacts

trigger: none

pool:
  vmImage: ubuntu-latest
variables:
  CI: 'true'
  # Set the release environment variable to build a release version of the wheel
  ONNX_SCRIPT_RELEASE: 1
steps:
  - template: _release-template.yml
