name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-python:
    name: Lint Python
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4.1.0
        with:
          python-version: "3.10"
      - name: misspell # Check spellings as well
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"
          reporter: github-pr-check
          level: info
          filter_mode: diff_context
      - name: shellcheck # Static check shell scripts
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: info
          filter_mode: diff_context

  enforce-style:
    name: Enforce style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4.1.0
        with:
          # Version range or exact version of Python to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: "3.10"
      - name: Install ONNXScript
        run: |
          # The code is from azure-pipelines.yml
          # Install dependencies
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install -q -r requirements-dev.txt
          # Install ONNX
          python -m pip uninstall -y onnx-function-experiment
          python -m pip uninstall -y ort-function-experiment-nightly
          python -m pip install onnx onnxruntime
          # install packages
          python -m pip install -e .
      - name: Run style.sh
        run: |
          bash tools/style.sh
  optional-style:
    name: Optional style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4.1.0
        with:
          # Version range or exact version of Python to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: "3.10"
      - name: Install ONNXScript
        run: |
          # The code is from azure-pipelines.yml
          # Install dependencies
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install -q -r requirements-dev.txt
          # Install ONNX
          python -m pip uninstall -y onnx-function-experiment
          python -m pip uninstall -y ort-function-experiment-nightly
          python -m pip install onnx onnxruntime
          # install packages
          python -m pip install -e .
      - name: Run style_optional.sh
        run: |
          bash tools/style_optional.sh
